const path = require('path');

const root = __dirname;

module.exports = {
    root,
    storage: path.join(root, 'storage'),
    html: path.join(root, 'index.html'),
    port: Number(process.env.NYXFLASH_PORT || 3000),
    host: '0.0.0.0',
    version: '5.2.0',
    clientHeader: 'nyxflash-web',
    maxFiles: 7,
    maxFileSize: 4 * 1024 * 1024 * 1024,
    maxJsonSize: 1024 * 1024,
    maxUploads: 2,
    maxUploadsPerIp: 2,
    maxConnections: 80,
    maxConnectionsPerIp: 20,
    maxRequestsPerMinute: 180,
    maxChangesPerMinute: 60,
    maxTreeEntries: 5000,
    maxStatsEntries: 20000,
    maxZipFiles: 20000,
    maxZipBytes: 3500 * 1024 * 1024,
    maxPathLength: 2048,
    maxNameLength: 255,
    maxFolderDepth: 64,
    maxTransfers: 8,
    maxTransfersPerIp: 4,
    maxActiveUploadBytes: 8 * 1024 * 1024 * 1024,
    minFreeSpace: 256 * 1024 * 1024,
    batchTtl: 10 * 60 * 1000,
    mime: {
        '.7z': 'application/x-7z-compressed',
        '.avi': 'video/x-msvideo',
        '.bmp': 'image/bmp',
        '.csv': 'text/csv; charset=utf-8',
        '.gif': 'image/gif',
        '.gz': 'application/gzip',
        '.html': 'text/html; charset=utf-8',
        '.ico': 'image/x-icon',
        '.jpeg': 'image/jpeg',
        '.jpg': 'image/jpeg',
        '.js': 'text/javascript; charset=utf-8',
        '.json': 'application/json; charset=utf-8',
        '.m4a': 'audio/mp4',
        '.mkv': 'video/x-matroska',
        '.mov': 'video/quicktime',
        '.mp3': 'audio/mpeg',
        '.mp4': 'video/mp4',
        '.pdf': 'application/pdf',
        '.png': 'image/png',
        '.svg': 'image/svg+xml',
        '.tar': 'application/x-tar',
        '.txt': 'text/plain; charset=utf-8',
        '.wav': 'audio/wav',
        '.webm': 'video/webm',
        '.webp': 'image/webp',
        '.zip': 'application/zip'
    }
};
